name: Proxy Download
on: [workflow_dispatch] # 手动触发

env:
  FILE_URL: "https://mfmmyzj.tvzlefsxadsv.hath.network:20001/h/1f8685788c58c87c312f905d299fde9e239fbd86-451680-1280-1807-wbp/keystamp=1754193900-bec7de69dd;fileindex=168502715;xres=1280/11.webp" # 替换为实际资源地址

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      # 下载文件
      - name: Download resource
        run: |
          curl -L -o target_file "${{ env.FILE_URL}}"
          ls -lh target_file  # 显示文件大小
        timeout-minutes: 30   # 超时保护

      # 直传 Artifacts
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-file
          path: target_file      # 仅上传原始文件
          retention-days: 2     # 保留2天（默认90天）
